/**
 * Mock Initial Classes & Reviews Data — Classdoor
 * Base inicial de turmas acadêmicas com quórum e avaliações completas para US04-US07.
 */

export const MOCK_CLASSES = [
  {
    id: 'cls-carlos-aed-2026-1',
    professorId: 'prof-a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    professorName: 'Dr. Carlos Eduardo Santos',
    courseId: 'crs-101a-2026-algoritmos',
    courseName: 'Algoritmos e Estruturas de Dados',
    courseCode: 'CC201',
    semester: '2026.1',
    classCode: 'Turma A',
    enrolledCount: 38,
    isEvaluationOpen: true,
  },
  {
    id: 'cls-carlos-ia-2026-1',
    professorId: 'prof-a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    professorName: 'Dr. Carlos Eduardo Santos',
    courseId: 'crs-106f-2026-inteligencia-artificial',
    courseName: 'Inteligência Artificial & Machine Learning',
    courseCode: 'CC405',
    semester: '2026.1',
    classCode: 'Turma B',
    enrolledCount: 29,
    isEvaluationOpen: true,
  },
  {
    id: 'cls-ana-es-2026-1',
    professorId: 'prof-b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e',
    professorName: 'Dra. Ana Paula Silveira',
    courseId: 'crs-102b-2026-eng-software',
    courseName: 'Engenharia de Software & Arquitetura',
    courseCode: 'CC302',
    semester: '2026.1',
    classCode: 'Turma A',
    enrolledCount: 42,
    isEvaluationOpen: true,
  },
  {
    id: 'cls-roberto-calc-2026-1',
    professorId: 'prof-c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f',
    professorName: 'Prof. Roberto Albuquerque',
    courseId: 'crs-103c-2026-calculo-1',
    courseName: 'Cálculo Diferencial e Integral I',
    courseCode: 'MAT101',
    semester: '2026.1',
    classCode: 'Turma C',
    enrolledCount: 45,
    isEvaluationOpen: true,
  },
  {
    id: 'cls-closed-sample',
    professorId: 'prof-a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    professorName: 'Dr. Carlos Eduardo Santos',
    courseId: 'crs-101a-2026-algoritmos',
    courseName: 'Algoritmos e Estruturas de Dados',
    courseCode: 'CC201',
    semester: '2025.2',
    classCode: 'Turma Encerrada',
    enrolledCount: 30,
    isEvaluationOpen: false,
  },
  {
    id: 'cls-low-quorum-sample',
    professorId: 'prof-a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    professorName: 'Dr. Carlos Eduardo Santos',
    courseId: 'crs-101a-2026-algoritmos',
    courseName: 'Algoritmos e Estruturas de Dados',
    courseCode: 'CC201',
    semester: '2026.1',
    classCode: 'Turma Especial Reduzida',
    enrolledCount: 3, // Abaixo do quórum mínimo (5)
    isEvaluationOpen: true,
  },
];

export const INITIAL_MOCK_REVIEWS = [
  {
    id: 'rev-001',
    professorId: 'prof-a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    courseId: 'crs-101a-2026-algoritmos',
    classId: 'cls-carlos-aed-2026-1',
    courseName: 'Algoritmos e Estruturas de Dados',
    semester: '2026.1',
    rating: 5.0,
    difficulty: 3.0,
    wouldRecommend: true,
    comment: 'Excelente didática! O professor Carlos explica ponteiros e grafos com exemplos práticos visuais. As provas cobram exatamente o que é exercitado nas listas.',
    tags: ['Didático', 'Provas Justas', 'Apoio Extraclasse'],
    isAnonymous: true,
    studentName: 'Estudante Anônimo',
    avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=Anonimo1',
    audit_hash: 'hash_seed_001_carlos_aed',
    upvotes: 14,
    upvotedBy: ['user-101', 'user-102'],
    createdAt: '2026-09-18T14:30:00.000Z',
  },
  {
    id: 'rev-002',
    professorId: 'prof-a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    courseId: 'crs-101a-2026-algoritmos',
    classId: 'cls-carlos-aed-2026-1',
    courseName: 'Algoritmos e Estruturas de Dados',
    semester: '2026.1',
    rating: 4.5,
    difficulty: 3.5,
    wouldRecommend: true,
    comment: 'Matéria exige dedicação nas listas semanais em C++, mas o professor sempre tira dúvidas no atendimento individual. Recomendo muito!',
    tags: ['Pontual', 'Listas Práticas'],
    isAnonymous: false,
    studentName: 'Lucas Silva',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LucasSilva&backgroundColor=b6e3f4',
    audit_hash: 'hash_seed_002_carlos_aed',
    upvotes: 9,
    upvotedBy: ['user-103'],
    createdAt: '2026-09-20T10:15:00.000Z',
  },
  {
    id: 'rev-003',
    professorId: 'prof-a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    courseId: 'crs-106f-2026-inteligencia-artificial',
    classId: 'cls-carlos-ia-2026-1',
    courseName: 'Inteligência Artificial & Machine Learning',
    semester: '2026.1',
    rating: 5.0,
    difficulty: 3.0,
    wouldRecommend: true,
    comment: 'Os projetos com Python e redes neurais foram os mais enriquecedores do semestre. Feedback rápido nos commits dos trabalhos.',
    tags: ['Didático', 'Projetos Práticos', 'Tópicos Avançados'],
    isAnonymous: true,
    studentName: 'Estudante Anônimo',
    avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=Anonimo2',
    audit_hash: 'hash_seed_003_carlos_ia',
    upvotes: 18,
    upvotedBy: ['user-101', 'user-104', 'user-105'],
    createdAt: '2026-09-22T16:45:00.000Z',
  },
  {
    id: 'rev-004',
    professorId: 'prof-b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e',
    courseId: 'crs-102b-2026-eng-software',
    classId: 'cls-ana-es-2026-1',
    courseName: 'Engenharia de Software & Arquitetura',
    semester: '2026.1',
    rating: 5.0,
    difficulty: 2.8,
    wouldRecommend: true,
    comment: 'A professora Ana Paula é fantástica. A metodologia de Scrum e Kanban aplicada nos projetos em grupo prepara perfeitamente para o mercado.',
    tags: ['Didática Exemplar', 'Materiais Claros', 'Acolhedora'],
    isAnonymous: true,
    studentName: 'Estudante Anônimo',
    avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=Anonimo3',
    audit_hash: 'hash_seed_004_ana_es',
    upvotes: 21,
    upvotedBy: ['user-101', 'user-102', 'user-103'],
    createdAt: '2026-09-19T11:00:00.000Z',
  },
  {
    id: 'rev-005',
    professorId: 'prof-c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f',
    courseId: 'crs-103c-2026-calculo-1',
    classId: 'cls-roberto-calc-2026-1',
    courseName: 'Cálculo Diferencial e Integral I',
    semester: '2026.1',
    rating: 4.5,
    difficulty: 4.2,
    wouldRecommend: true,
    comment: 'Rigoroso com a matemática, mas muito justo. Se você fizer todas as listas e comparecer à monitoria, passa com folga.',
    tags: ['Exigente', 'Domina o Conteúdo'],
    isAnonymous: false,
    studentName: 'Mariana Duarte',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MarianaDuarte&backgroundColor=ffdfbf',
    audit_hash: 'hash_seed_005_roberto_calc',
    upvotes: 8,
    upvotedBy: [],
    createdAt: '2026-09-21T09:30:00.000Z',
  },
];
