/**
 * Mock Catalog Data — Classdoor
 * Base de dados simulada contendo 12+ Professores, 12+ Disciplinas e Departamentos acadêmicos.
 * Alinhado aos contratos da US03 (Contratos-Integracao-User-Stories.md e Especificacao-Design-System-Figma.md).
 */

export const DEPARTMENTS = [
  'Ciência da Computação',
  'Engenharia Elétrica',
  'Matemática & Estatística',
  'Física Aplicada',
  'Sistemas de Informação',
  'Administração & Negócios',
  'Design & Mídia Digital'
];

export const MOCK_PROFESSORS = [
  {
    id: 'prof-a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    name: 'Dr. Carlos Eduardo Santos',
    title: 'Professor Doutor',
    department: 'Ciência da Computação',
    university: 'Universidade Federal',
    email: 'carlos.santos@universidade.edu.br',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CarlosSantos&backgroundColor=b6e3f4',
    averageRating: 4.8,
    difficultyRating: 3.2,
    recommendationPercentage: 96,
    totalReviews: 48,
    topTags: ['Didático', 'Provas Justas', 'Pontual', 'Apoio Extraclasse'],
    bio: 'Especialista em Algoritmos e Inteligência Artificial. Aulas dinâmicas com foco em projetos práticos.',
    featured: true,
    coursesTaught: ['Algoritmos e Estruturas de Dados', 'Inteligência Artificial', 'Compiladores']
  },
  {
    id: 'prof-b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e',
    name: 'Dra. Ana Paula Silveira',
    title: 'Professora Doutora',
    department: 'Ciência da Computação',
    university: 'Universidade Federal',
    email: 'ana.silveira@universidade.edu.br',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AnaSilveira&backgroundColor=ffdfbf',
    averageRating: 4.9,
    difficultyRating: 2.8,
    recommendationPercentage: 98,
    totalReviews: 54,
    topTags: ['Didática Exemplar', 'Materiais Claros', 'Acolhedora', 'Projetos Práticos'],
    bio: 'Pesquisadora em Engenharia de Software e Interação Humano-Computador. Foco em arquitetura limpa.',
    featured: true,
    coursesTaught: ['Engenharia de Software & Arquitetura', 'Interação Humano-Computador', 'Padrões de Projeto']
  },
  {
    id: 'prof-c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f',
    name: 'Prof. Roberto Albuquerque',
    title: 'Professor Mestre',
    department: 'Matemática & Estatística',
    university: 'Universidade Federal',
    email: 'roberto.albuquerque@universidade.edu.br',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RobertoAlbuquerque&backgroundColor=c0aede',
    averageRating: 4.5,
    difficultyRating: 4.1,
    recommendationPercentage: 89,
    totalReviews: 36,
    topTags: ['Exigente', 'Domina o Conteúdo', 'Listas Extensas', 'Aulas Gravadas'],
    bio: 'Dedicado ao ensino de Cálculo e Geometria Analítica. Conhecido por rigor matemático e excelente suporte.',
    featured: true,
    coursesTaught: ['Cálculo Diferencial e Integral I', 'Álgebra Linear', 'Cálculo Numérico']
  },
  {
    id: 'prof-d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f90',
    name: 'Dra. Juliana Mendes Rocha',
    title: 'Professora Doutora',
    department: 'Sistemas de Informação',
    university: 'Universidade Federal',
    email: 'juliana.rocha@universidade.edu.br',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=JulianaRocha&backgroundColor=ffd5dc',
    averageRating: 4.7,
    difficultyRating: 3.0,
    recommendationPercentage: 94,
    totalReviews: 41,
    topTags: ['Inovadora', 'Trabalho em Grupo', 'Feedback Rápido', 'Provas Claras'],
    bio: 'Especialista em Banco de Dados e Governança de TI. Metodologias ágeis e estudos de caso corporativos.',
    featured: true,
    coursesTaught: ['Banco de Dados Relacional & NoSQL', 'Modelagem de Sistemas', 'Gestão de Projetos de TI']
  },
  {
    id: 'prof-e5f6a7b8-c9d0-1e2f-3a4b-5c6d7e8f90a1',
    name: 'Prof. Marcelo Henrique Lima',
    title: 'Professor Doutor',
    department: 'Engenharia Elétrica',
    university: 'Universidade Federal',
    email: 'marcelo.lima@universidade.edu.br',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MarceloLima&backgroundColor=d1d4f9',
    averageRating: 4.3,
    difficultyRating: 4.4,
    recommendationPercentage: 82,
    totalReviews: 29,
    topTags: ['Exigente', 'Laboratórios Práticos', 'Muito Conhecimento'],
    bio: 'Pesquisador em Circuitos Integrados, Microeletrônica e Sistemas Embarcados.',
    featured: false,
    coursesTaught: ['Circuitos Elétricos I', 'Eletrônica Digital', 'Sistemas Embarcados']
  },
  {
    id: 'prof-f6a7b8c9-d0e1-2f3a-4b5c-6d7e8f90a1b2',
    name: 'Dra. Fernanda Vasconcelos',
    title: 'Professora Doutora',
    department: 'Design & Mídia Digital',
    university: 'Universidade Federal',
    email: 'fernanda.vasconcelos@universidade.edu.br',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FernandaVasc&backgroundColor=ffdfbf',
    averageRating: 4.9,
    difficultyRating: 2.5,
    recommendationPercentage: 99,
    totalReviews: 38,
    topTags: ['Muito Didática', 'Projetos Criativos', 'Avaliação Contínua', 'Inspiradora'],
    bio: 'Especialista em UX/UI, Design Systems, Usabilidade e Acessibilidade Digital.',
    featured: true,
    coursesTaught: ['Design de Interfaces & UX (UI/UX)', 'Design Systems', 'Tipografia & Identidade Visual']
  },
  {
    id: 'prof-a7b8c9d0-e1f2-3a4b-5c6d-7e8f90a1b2c3',
    name: 'Dr. Lucas Guimarães Prado',
    title: 'Professor Doutor',
    department: 'Ciência da Computação',
    university: 'Universidade Federal',
    email: 'lucas.prado@universidade.edu.br',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LucasGuimaraes&backgroundColor=b6e3f4',
    averageRating: 4.6,
    difficultyRating: 3.5,
    recommendationPercentage: 91,
    totalReviews: 33,
    topTags: ['Mão na Massa', 'Projetos em Nuvem', 'Mercado de Trabalho'],
    bio: 'Docente e pesquisador nas áreas de Redes de Computadores, Cloud Computing e Segurança Cibernética.',
    featured: false,
    coursesTaught: ['Redes de Computadores', 'Computação em Nuvem', 'Segurança da Informação']
  },
  {
    id: 'prof-b8c9d0e1-f2a3-4b5c-6d7e-8f90a1b2c3d4',
    name: 'Dra. Beatriz Toledo Neves',
    title: 'Professora Doutora',
    department: 'Administração & Negócios',
    university: 'Universidade Federal',
    email: 'beatriz.neves@universidade.edu.br',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BeatrizNeves&backgroundColor=ffd5dc',
    averageRating: 4.8,
    difficultyRating: 2.9,
    recommendationPercentage: 95,
    totalReviews: 44,
    topTags: ['Participativa', 'Casos Reais', 'Empática', 'Sem Prova Tradicional'],
    bio: 'Empreendedorismo, Startups, Gestão da Inovação e Modelos de Negócios Digitais.',
    featured: false,
    coursesTaught: ['Empreendedorismo e Inovação', 'Modelos de Negócios', 'Marketing Digital']
  },
  {
    id: 'prof-c9d0e1f2-a3b4-5c6d-7e8f-90a1b2c3d4e5',
    name: 'Dr. Fernando Augusto Ramos',
    title: 'Professor Doutor',
    department: 'Física Aplicada',
    university: 'Universidade Federal',
    email: 'fernando.ramos@universidade.edu.br',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FernandoRamos&backgroundColor=c0aede',
    averageRating: 4.4,
    difficultyRating: 4.3,
    recommendationPercentage: 86,
    totalReviews: 31,
    topTags: ['Rigoroso', 'Demonstrações Visuais', 'Disponível para Dúvidas'],
    bio: 'Pesquisador em Óptica Quântica, Eletromagnetismo e Física Experimental.',
    featured: false,
    coursesTaught: ['Física Geral I (Mecânica)', 'Física Geral III (Eletromagnetismo)', 'Física Experimental']
  },
  {
    id: 'prof-d0e1f2a3-b4c5-6d7e-8f90-a1b2c3d4e5f6',
    name: 'Dra. Camila Nogueira Dantas',
    title: 'Professora Doutora',
    department: 'Matemática & Estatística',
    university: 'Universidade Federal',
    email: 'camila.dantas@universidade.edu.br',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CamilaDantas&backgroundColor=ffdfbf',
    averageRating: 4.7,
    difficultyRating: 3.4,
    recommendationPercentage: 93,
    totalReviews: 39,
    topTags: ['Excelente Didática', 'Exercícios Práticos', 'Monitoria Ativa'],
    bio: 'Estatística Aplicada, Probabilidade e Análise de Séries Temporais.',
    featured: false,
    coursesTaught: ['Probabilidade & Estatística', 'Inferência Estatística', 'Análise de Dados']
  },
  {
    id: 'prof-e1f2a3b4-c5d6-7e8f-90a1-b2c3d4e5f6a7',
    name: 'Prof. Gabriel Valença Brandão',
    title: 'Professor Mestre',
    department: 'Sistemas de Informação',
    university: 'Universidade Federal',
    email: 'gabriel.brandao@universidade.edu.br',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=GabrielBrandao&backgroundColor=d1d4f9',
    averageRating: 4.8,
    difficultyRating: 2.7,
    recommendationPercentage: 97,
    totalReviews: 46,
    topTags: ['Aulas Interativas', 'Foco em Mercado', 'Projetos Web'],
    bio: 'Desenvolvimento Web Fullstack, Arquitetura de Microsserviços e DevOps.',
    featured: true,
    coursesTaught: ['Desenvolvimento Web Full Stack', 'Arquitetura de Software', 'Engenharia de Requisitos']
  },
  {
    id: 'prof-f2a3b4c5-d6e7-8f90-a1b2-c3d4e5f6a7b8',
    name: 'Dra. Helena Martins Fonseca',
    title: 'Professora Doutora',
    department: 'Engenharia Elétrica',
    university: 'Universidade Federal',
    email: 'helena.fonseca@universidade.edu.br',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=HelenaFonseca&backgroundColor=ffd5dc',
    averageRating: 4.6,
    difficultyRating: 3.9,
    recommendationPercentage: 90,
    totalReviews: 35,
    topTags: ['Muito Dedicada', 'Trabalhos Práticos', 'Feedback Detalhado'],
    bio: 'Sistemas de Controle, Automação Industrial e Robótica Móvel.',
    featured: false,
    coursesTaught: ['Sistemas de Controle Linear', 'Automação & Robótica', 'Processamento de Sinais']
  }
];

export const MOCK_COURSES = [
  {
    id: 'crs-101a-2026-alg-est-dados',
    code: 'CC201',
    name: 'Algoritmos e Estruturas de Dados',
    department: 'Ciência da Computação',
    credits: 4,
    syllabus: 'Listas encadeadas, pilhas, filas, árvores binárias, balanceamento AVL/Red-Black, grafos, ordenação e análise assintótica.',
    averageRating: 4.7,
    difficultyRating: 3.8,
    recommendationPercentage: 93,
    totalReviews: 62,
    topTags: ['Essencial para o Curso', 'Desafiadora', 'Projetos Práticos', 'Boa Monitoria'],
    featured: true,
    semester: '2º Semestre'
  },
  {
    id: 'crs-102b-2026-eng-software',
    code: 'CC302',
    name: 'Engenharia de Software & Arquitetura',
    department: 'Ciência da Computação',
    credits: 4,
    syllabus: 'Padrões de projeto, Clean Architecture, SOLID, testes automatizados, integração contínua (CI/CD) e processos ágeis.',
    averageRating: 4.9,
    difficultyRating: 2.9,
    recommendationPercentage: 97,
    totalReviews: 58,
    topTags: ['Alinhada ao Mercado', 'Projetos em Grupo', 'Sem Prova Decoreba'],
    featured: true,
    semester: '4º Semestre'
  },
  {
    id: 'crs-103c-2026-calc-dif-int-1',
    code: 'MAT101',
    name: 'Cálculo Diferencial e Integral I',
    department: 'Matemática & Estatística',
    credits: 6,
    syllabus: 'Limites, continuidade, regras de derivação, taxas relacionadas, otimização e introdução a integrais de Riemann.',
    averageRating: 4.2,
    difficultyRating: 4.5,
    recommendationPercentage: 81,
    totalReviews: 89,
    topTags: ['Alta Exigência', 'Exige Estudo Diário', 'Monitoria Necessária', 'Base Fundamental'],
    featured: true,
    semester: '1º Semestre'
  },
  {
    id: 'crs-104d-2026-banco-de-dados',
    code: 'SI204',
    name: 'Banco de Dados Relacional & NoSQL',
    department: 'Sistemas de Informação',
    credits: 4,
    syllabus: 'Modelagem entidade-relacionamento, álgebra relacional, normalização, consultas SQL avançadas e bancos NoSQL orientados a documentos.',
    averageRating: 4.8,
    difficultyRating: 3.1,
    recommendationPercentage: 95,
    totalReviews: 47,
    topTags: ['Muito Prática', 'Consultas Complexas', 'Excelente Material'],
    featured: true,
    semester: '3º Semestre'
  },
  {
    id: 'crs-105e-2026-ui-ux-design',
    code: 'DES105',
    name: 'Design de Interfaces & UX (UI/UX)',
    department: 'Design & Mídia Digital',
    credits: 4,
    syllabus: 'Pesquisa com usuários, mapas de empatia, wireframing, prototipação no Figma, Design Systems e testes de usabilidade.',
    averageRating: 4.9,
    difficultyRating: 2.6,
    recommendationPercentage: 98,
    totalReviews: 51,
    topTags: ['Prática Criativa', 'Portfólio Real', 'Figma & Design Tokens'],
    featured: true,
    semester: '3º Semestre'
  },
  {
    id: 'crs-106f-2026-inteligencia-artificial',
    code: 'CC405',
    name: 'Inteligência Artificial & Machine Learning',
    department: 'Ciência da Computação',
    credits: 4,
    syllabus: 'Busca heurística, regressão, classificação supervisionada, redes neurais profundas e introdução a modelos generativos (LLMs).',
    averageRating: 4.8,
    difficultyRating: 3.7,
    recommendationPercentage: 94,
    totalReviews: 43,
    topTags: ['Moderno', 'Projetos com Python', 'Tópicos Avançados'],
    featured: true,
    semester: '6º Semestre'
  },
  {
    id: 'crs-107g-2026-redes-computadores',
    code: 'CC308',
    name: 'Redes de Computadores & Protocolos',
    department: 'Ciência da Computação',
    credits: 4,
    syllabus: 'Modelo OSI e TCP/IP, camadas de aplicação, transporte (TCP/UDP), roteamento IP, enlace e segurança em redes.',
    averageRating: 4.5,
    difficultyRating: 3.6,
    recommendationPercentage: 90,
    totalReviews: 37,
    topTags: ['Laboratório com Wireshark', 'Muito Conteúdo', 'Exames Objetivos'],
    featured: false,
    semester: '5º Semestre'
  },
  {
    id: 'crs-108h-2026-probabilidade-estatistica',
    code: 'MAT203',
    name: 'Probabilidade & Estatística Aplicada',
    department: 'Matemática & Estatística',
    credits: 4,
    syllabus: 'Espaços amostrais, variáveis aleatórias discretas e contínuas, distribuições de probabilidade, intervalos de confiança e testes de hipóteses.',
    averageRating: 4.6,
    difficultyRating: 3.4,
    recommendationPercentage: 91,
    totalReviews: 45,
    topTags: ['Aplicações em R e Python', 'Listas Semanais', 'Monitoria Presente'],
    featured: false,
    semester: '3º Semestre'
  },
  {
    id: 'crs-109i-2026-circuitos-eletricos-1',
    code: 'EE102',
    name: 'Circuitos Elétricos I & Laboratório',
    department: 'Engenharia Elétrica',
    credits: 6,
    syllabus: 'Leis de Kirchhoff, análise nodal e de malhas, teoremas de Thévenin e Norton, transitórios de primeira e segunda ordem em circuitos RLC.',
    averageRating: 4.3,
    difficultyRating: 4.3,
    recommendationPercentage: 83,
    totalReviews: 32,
    topTags: ['Aulas Práticas no Lab', 'Relatórios Semanais', 'Alta Exigência'],
    featured: false,
    semester: '3º Semestre'
  },
  {
    id: 'crs-110j-2026-dev-web-fullstack',
    code: 'SI305',
    name: 'Desenvolvimento Web Full Stack',
    department: 'Sistemas de Informação',
    credits: 4,
    syllabus: 'Front-end moderno com React, Node.js/Express e Spring Boot no backend, APIs RESTful, autenticação JWT e deploy em nuvem.',
    averageRating: 4.9,
    difficultyRating: 2.8,
    recommendationPercentage: 98,
    totalReviews: 53,
    topTags: ['Muito Prática', 'Stack Atualizada', 'Projeto Final Completo'],
    featured: true,
    semester: '4º Semestre'
  },
  {
    id: 'crs-111k-2026-empreendedorismo-inovacao',
    code: 'ADM210',
    name: 'Empreendedorismo & Modelos de Negócios',
    department: 'Administração & Negócios',
    credits: 2,
    syllabus: 'Metodologia Lean Startup, Business Model Canvas, validação com clientes, pitch decks e captação de investimento.',
    averageRating: 4.7,
    difficultyRating: 2.4,
    recommendationPercentage: 95,
    totalReviews: 40,
    topTags: ['Pitch com Avaliadores', 'Metodologia Ágil', 'Excelente Dinâmica'],
    featured: false,
    semester: '5º Semestre'
  },
  {
    id: 'crs-112l-2026-fisica-geral-1',
    code: 'FIS101',
    name: 'Física Geral I (Mecânica Clássica)',
    department: 'Física Aplicada',
    credits: 4,
    syllabus: 'Cinemática vetorial, Leis de Newton, trabalho e energia cinética, conservação do momento linear, colisões e rotação de corpos rígidos.',
    averageRating: 4.1,
    difficultyRating: 4.6,
    recommendationPercentage: 79,
    totalReviews: 67,
    topTags: ['Cálculo Intenso', 'Exige Dedicação', 'Listas Extensas'],
    featured: false,
    semester: '1º Semestre'
  }
];
